# docker-compose.prod.yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
    env_file: .env.prod
    ports:
      - "8000:8000"
    restart: always


# Launch the UAT container manually
# docker compose -f docker-compose.prod.yml up --build