# docker-compose.uat.yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=uat
    env_file: .env.prod
    ports:
      - "8001:8000"
    restart: always


# Launch the UAT container manually
# docker compose -f docker-compose.uat.yml up --build