version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always
    # If needed:
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    
    # Launch the UAT container manually
    # docker compose -f docker-compose.uat.yml up --build