version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ENV=uat

    # Use a command if you didn't define CMD in Dockerfile:
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

    # Launch the UAT container manually
    # docker compose -f docker-compose.uat.yml up --build
